apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: rlee10icf-go 
  janus-idp.io/tekton: rlee10icf-go
  backstage.io/kubernetes-id: rlee10icf-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: rlee10icf-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml