apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rlee10icf-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rlee10icf-go 
  name: rlee10icf-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rlee10icf-go 
